### ISSUE TITLE
stop build based on scan exit code

### ISSUE THREAD

**Issue by cji** [heroku/ciclair#1]
If the clair scan fails and exits with a non 0 code, we should prevent the CI script from continuing and stop it from pushing to a registry

**Comment by mattreduce** [comment]
![](https://media.giphy.com/media/cdr4V05plfxv2/giphy.gif)

**Comment by cji** [comment]
fixed! https://github.com/heroku/ciclair/blob/361c7799e5c923c768855834f081c919cb231bd0/bin/run-clair.sh#L44
